version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    groups:
      eslint:
        patterns:
          - '*eslint*'
      prettier:
        patterns:
          - '*prettier*'
      security-all:
        applies-to: 'security-updates'
        patterns:
          - '*'
      version-all:
        applies-to: 'version-updates'
        patterns:
          - '*'
